#server:
#  port: 8081
#spring:
#  application:
#    name: provider-demo
#  datasource:
#    url: jdbc:mysql://121.4.78.71
#    username: liubenwei
#    password: liubenwei
#dubbo:
#  application:
#    name: provider-demo
#  registry:
#    address: nacos://127.0.0.1:8848
#  protocol:
#    name: dubbo
#    port: 20881
#    threads: 1
#  provider:
#    group: demo
#    version: 1.0
#    retries: 1
